# Generated by Django 5.2.1 on 2025-05-27 04:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GeminiUsageStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Fecha')),
                ('total_requests', models.IntegerField(default=0, verbose_name='Total de requests')),
                ('total_input_tokens', models.IntegerField(default=0, verbose_name='Total tokens de entrada')),
                ('total_output_tokens', models.IntegerField(default=0, verbose_name='Total tokens de salida')),
                ('total_cost_usd', models.DecimalField(decimal_places=6, default=0, max_digits=10, verbose_name='Costo total USD')),
                ('successful_analyses', models.IntegerField(default=0, verbose_name='Análisis exitosos')),
                ('failed_analyses', models.IntegerField(default=0, verbose_name='Análisis fallidos')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Estadísticas de Uso de Gemini',
                'verbose_name_plural': 'Estadísticas de Uso de Gemini',
                'db_table': 'ai_analysis_geminiusagestats',
                'indexes': [models.Index(fields=['user', 'date'], name='ai_analysis_user_id_03998a_idx'), models.Index(fields=['date'], name='ai_analysis_date_e0135c_idx')],
                'unique_together': {('user', 'date')},
            },
        ),
        migrations.CreateModel(
            name='ImageAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_size', models.IntegerField(blank=True, null=True, verbose_name='Tamaño de imagen (bytes)')),
                ('image_format', models.CharField(blank=True, max_length=10, null=True, verbose_name='Formato de imagen')),
                ('gemini_request_tokens', models.IntegerField(blank=True, null=True, verbose_name='Tokens de request')),
                ('gemini_response_tokens', models.IntegerField(blank=True, null=True, verbose_name='Tokens de response')),
                ('gemini_cost_usd', models.DecimalField(blank=True, decimal_places=6, max_digits=8, null=True, verbose_name='Costo en USD')),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('processing', 'Procesando'), ('completed', 'Completado'), ('failed', 'Fallido'), ('error', 'Error')], default='pending', max_length=20, verbose_name='Estado')),
                ('error_message', models.TextField(blank=True, verbose_name='Mensaje de error')),
                ('raw_ai_response', models.JSONField(blank=True, null=True, verbose_name='Respuesta cruda de IA')),
                ('processing_time_seconds', models.FloatField(blank=True, null=True, verbose_name='Tiempo de procesamiento (s)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Análisis de Imagen',
                'verbose_name_plural': 'Análisis de Imágenes',
                'db_table': 'ai_analysis_imageanalysis',
                'indexes': [models.Index(fields=['user', 'status'], name='ai_analysis_user_id_a3966f_idx'), models.Index(fields=['created_at'], name='ai_analysis_created_382c3f_idx'), models.Index(fields=['status'], name='ai_analysis_status_92cc0f_idx')],
            },
        ),
    ]
