# Generated by Django 5.2.1 on 2025-05-27 02:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FitnessGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goal_type', models.CharField(choices=[('weight_loss', 'Bajar de peso'), ('muscle_gain', 'Ganar musculatura'), ('maintenance', 'Mantener peso actual'), ('recomposition', 'Recomposición corporal')], help_text='Objetivo fitness principal', max_length=20, verbose_name='Tipo de objetivo')),
                ('is_active', models.BooleanField(default=True, help_text='Si este objetivo está actualmente activo', verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Objetivo Fitness',
                'verbose_name_plural': 'Objetivos Fitness',
                'db_table': 'nutrition_fitnessgoal',
            },
        ),
        migrations.CreateModel(
            name='NutritionTargets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(help_text='Fecha para la cual aplican estas metas', verbose_name='Fecha')),
                ('calories', models.IntegerField(verbose_name='Calorías objetivo')),
                ('protein', models.FloatField(verbose_name='Proteínas objetivo (g)')),
                ('carbs', models.FloatField(verbose_name='Carbohidratos objetivo (g)')),
                ('fat', models.FloatField(verbose_name='Grasas objetivo (g)')),
                ('bmi', models.FloatField(verbose_name='IMC')),
                ('tdee', models.IntegerField(verbose_name='TDEE')),
                ('bmr', models.IntegerField(verbose_name='TMB')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('fitness_goal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nutrition.fitnessgoal', verbose_name='Objetivo fitness')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Metas Nutricionales',
                'verbose_name_plural': 'Metas Nutricionales',
                'db_table': 'nutrition_targets',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.FloatField(help_text='Peso en kilogramos', verbose_name='Peso')),
                ('height', models.FloatField(help_text='Altura en centímetros', verbose_name='Altura')),
                ('age', models.PositiveIntegerField(help_text='Edad en años', verbose_name='Edad')),
                ('gender', models.CharField(choices=[('male', 'Masculino'), ('female', 'Femenino')], help_text='Género del usuario', max_length=10, verbose_name='Género')),
                ('activity_level', models.FloatField(choices=[(1.2, 'Sedentario (poco o ningún ejercicio)'), (1.375, 'Ejercicio ligero (1-3 días/semana)'), (1.55, 'Ejercicio moderado (3-5 días/semana)'), (1.725, 'Ejercicio intenso (6-7 días/semana)'), (1.9, 'Ejercicio muy intenso (dos veces al día, trabajos físicos)')], help_text='Nivel de actividad física', verbose_name='Nivel de actividad')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='nutrition_profile', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Perfil Nutricional',
                'verbose_name_plural': 'Perfiles Nutricionales',
                'db_table': 'nutrition_userprofile',
            },
        ),
        migrations.AddIndex(
            model_name='fitnessgoal',
            index=models.Index(fields=['user', 'is_active'], name='nutrition_f_user_id_4df04c_idx'),
        ),
        migrations.AddIndex(
            model_name='fitnessgoal',
            index=models.Index(fields=['created_at'], name='nutrition_f_created_babe27_idx'),
        ),
        migrations.AddIndex(
            model_name='nutritiontargets',
            index=models.Index(fields=['user', 'date'], name='nutrition_t_user_id_99f4fd_idx'),
        ),
        migrations.AddIndex(
            model_name='nutritiontargets',
            index=models.Index(fields=['created_at'], name='nutrition_t_created_18f468_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='nutritiontargets',
            unique_together={('user', 'date')},
        ),
        migrations.AddIndex(
            model_name='userprofile',
            index=models.Index(fields=['user'], name='nutrition_u_user_id_2d5b1e_idx'),
        ),
        migrations.AddIndex(
            model_name='userprofile',
            index=models.Index(fields=['created_at'], name='nutrition_u_created_5305aa_idx'),
        ),
    ]
