# Generated by Django 5.2.1 on 2025-05-27 03:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('foods', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Fecha')),
                ('total_calories', models.FloatField(default=0, verbose_name='Total calorías')),
                ('total_protein', models.FloatField(default=0, verbose_name='Total proteínas (g)')),
                ('total_carbs', models.FloatField(default=0, verbose_name='Total carbohidratos (g)')),
                ('total_fat', models.FloatField(default=0, verbose_name='Total grasas (g)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Registro Diario',
                'verbose_name_plural': 'Registros Diarios',
                'db_table': 'tracking_dailylog',
            },
        ),
        migrations.CreateModel(
            name='LoggedFoodItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre')),
                ('quantity', models.FloatField(verbose_name='Cantidad')),
                ('unit', models.CharField(max_length=20, verbose_name='Unidad')),
                ('calories', models.FloatField(verbose_name='Calorías')),
                ('protein', models.FloatField(verbose_name='Proteínas (g)')),
                ('carbs', models.FloatField(verbose_name='Carbohidratos (g)')),
                ('fat', models.FloatField(verbose_name='Grasas (g)')),
                ('meal_type', models.CharField(choices=[('breakfast', 'Desayuno'), ('lunch', 'Almuerzo'), ('dinner', 'Cena'), ('snack', 'Snack'), ('other', 'Otro')], default='other', max_length=20, verbose_name='Tipo de comida')),
                ('logged_at', models.DateTimeField(auto_now_add=True)),
                ('daily_log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='food_items', to='tracking.dailylog', verbose_name='Registro diario')),
                ('food', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='foods.food', verbose_name='Alimento')),
                ('scanned_food', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='foods.scannedfood', verbose_name='Alimento escaneado')),
            ],
            options={
                'verbose_name': 'Alimento Registrado',
                'verbose_name_plural': 'Alimentos Registrados',
                'db_table': 'tracking_loggedfooditem',
            },
        ),
        migrations.AddIndex(
            model_name='dailylog',
            index=models.Index(fields=['user', 'date'], name='tracking_da_user_id_360749_idx'),
        ),
        migrations.AddIndex(
            model_name='dailylog',
            index=models.Index(fields=['created_at'], name='tracking_da_created_79f665_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='dailylog',
            unique_together={('user', 'date')},
        ),
        migrations.AddIndex(
            model_name='loggedfooditem',
            index=models.Index(fields=['daily_log', 'logged_at'], name='tracking_lo_daily_l_e2950c_idx'),
        ),
        migrations.AddIndex(
            model_name='loggedfooditem',
            index=models.Index(fields=['meal_type'], name='tracking_lo_meal_ty_d29984_idx'),
        ),
    ]
